title:              Dongok Nam Blog
email:              dongoknam@gist.ac.kr
description:        A blog for studying biology and deep learning 
author:             Dongok Nam
baseurl:            ""
url:                "https://dongoknam.github.io"

# Social Profiles
github_username:    dongoknam
facebook_username:  ndo7674@gmail.com
instagram_username:  namdo1
linkedin_username:   ndo7674

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jemoji
